name: Get Unity License

on:
  workflow_dispatch:

jobs:
  request-alf:
    runs-on: ubuntu-latest
    steps:
      - name: Request activation file
        uses: game-ci/unity-request-activation-file@main
        id: getAlf
        
      - name: Upload ALF
        uses: actions/upload-artifact@v4
        with:
          name: Unity-ALF
          path: ${{ steps.getAlf.outputs.filePath }}
          retention-days: 1
