name: Acquire Unity License

on:
  workflow_dispatch:

jobs:
  acquire:
    runs-on: ubuntu-latest
    steps:
      - name: Request Manual Activation File
        uses: game-ci/unity-request-activation-file@v2
        id: getManualLicenseFile
        with:
          unityVersion: 2022.3.22f1

      - name: Upload Activation File
        uses: actions/upload-artifact@v4
        with:
          name: Unity_Activation_File
          path: ${{ steps.getManualLicenseFile.outputs.filePath }}
